# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'builder.ui'
#
# Created: Mon May 22 10:30:45 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_pandapower(object):
    def setupUi(self, pandapower):
        pandapower.setObjectName("pandapower")
        pandapower.resize(1023, 702)
        self.centralwidget = QtGui.QWidget(pandapower)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1011, 661))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(self.verticalLayoutWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.main = QtGui.QWidget()
        self.main.setObjectName("main")
        self.main_save = QtGui.QPushButton(self.main)
        self.main_save.setGeometry(QtCore.QRect(10, 90, 91, 31))
        self.main_save.setObjectName("main_save")
        self.main_losses = QtGui.QPushButton(self.main)
        self.main_losses.setGeometry(QtCore.QRect(10, 170, 91, 31))
        self.main_losses.setObjectName("main_losses")
        self.main_load = QtGui.QPushButton(self.main)
        self.main_load.setGeometry(QtCore.QRect(10, 50, 91, 31))
        self.main_load.setObjectName("main_load")
        self.main_solve = QtGui.QPushButton(self.main)
        self.main_solve.setGeometry(QtCore.QRect(10, 130, 91, 31))
        self.main_solve.setObjectName("main_solve")
        self.main_message = QtGui.QTextBrowser(self.main)
        self.main_message.setGeometry(QtCore.QRect(110, 10, 861, 581))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 127, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 56, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 127, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 56, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 127, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 56, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.main_message.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.main_message.setFont(font)
        self.main_message.setProperty("cursor", QtCore.Qt.ArrowCursor)
        self.main_message.setFrameShape(QtGui.QFrame.Box)
        self.main_message.setFrameShadow(QtGui.QFrame.Plain)
        self.main_message.setObjectName("main_message")
        self.main_empty = QtGui.QPushButton(self.main)
        self.main_empty.setGeometry(QtCore.QRect(10, 10, 91, 31))
        self.main_empty.setObjectName("main_empty")
        self.tabWidget.addTab(self.main, "")
        self.inspect = QtGui.QWidget()
        self.inspect.setObjectName("inspect")
        self.inspect_ext_grid = QtGui.QPushButton(self.inspect)
        self.inspect_ext_grid.setGeometry(QtCore.QRect(10, 160, 91, 31))
        self.inspect_ext_grid.setObjectName("inspect_ext_grid")
        self.inspect_xward = QtGui.QPushButton(self.inspect)
        self.inspect_xward.setGeometry(QtCore.QRect(10, 370, 91, 31))
        self.inspect_xward.setObjectName("inspect_xward")
        self.inspect_load = QtGui.QPushButton(self.inspect)
        self.inspect_load.setGeometry(QtCore.QRect(10, 100, 91, 31))
        self.inspect_load.setObjectName("inspect_load")
        self.inspect_dcline = QtGui.QPushButton(self.inspect)
        self.inspect_dcline.setGeometry(QtCore.QRect(10, 400, 91, 31))
        self.inspect_dcline.setObjectName("inspect_dcline")
        self.inspect_shunt = QtGui.QPushButton(self.inspect)
        self.inspect_shunt.setGeometry(QtCore.QRect(10, 280, 91, 31))
        self.inspect_shunt.setObjectName("inspect_shunt")
        self.inspect_trafo = QtGui.QPushButton(self.inspect)
        self.inspect_trafo.setGeometry(QtCore.QRect(10, 190, 91, 31))
        self.inspect_trafo.setObjectName("inspect_trafo")
        self.inspect_trafo3w = QtGui.QPushButton(self.inspect)
        self.inspect_trafo3w.setGeometry(QtCore.QRect(10, 220, 91, 31))
        self.inspect_trafo3w.setObjectName("inspect_trafo3w")
        self.inspect_gen = QtGui.QPushButton(self.inspect)
        self.inspect_gen.setGeometry(QtCore.QRect(10, 250, 91, 31))
        self.inspect_gen.setObjectName("inspect_gen")
        self.inspect_impedance = QtGui.QPushButton(self.inspect)
        self.inspect_impedance.setGeometry(QtCore.QRect(10, 310, 91, 31))
        self.inspect_impedance.setObjectName("inspect_impedance")
        self.inspect_sgen = QtGui.QPushButton(self.inspect)
        self.inspect_sgen.setGeometry(QtCore.QRect(10, 130, 91, 31))
        self.inspect_sgen.setObjectName("inspect_sgen")
        self.inspect_switch = QtGui.QPushButton(self.inspect)
        self.inspect_switch.setGeometry(QtCore.QRect(10, 70, 91, 31))
        self.inspect_switch.setObjectName("inspect_switch")
        self.inspect_measurement = QtGui.QPushButton(self.inspect)
        self.inspect_measurement.setGeometry(QtCore.QRect(10, 430, 91, 31))
        self.inspect_measurement.setObjectName("inspect_measurement")
        self.inspect_ward = QtGui.QPushButton(self.inspect)
        self.inspect_ward.setGeometry(QtCore.QRect(10, 340, 91, 31))
        self.inspect_ward.setObjectName("inspect_ward")
        self.inspect_message = QtGui.QTextBrowser(self.inspect)
        self.inspect_message.setGeometry(QtCore.QRect(110, 10, 861, 581))
        self.inspect_message.setFrameShape(QtGui.QFrame.Box)
        self.inspect_message.setObjectName("inspect_message")
        self.inspect_lines = QtGui.QPushButton(self.inspect)
        self.inspect_lines.setGeometry(QtCore.QRect(10, 40, 91, 31))
        self.inspect_lines.setObjectName("inspect_lines")
        self.inspect_bus = QtGui.QPushButton(self.inspect)
        self.inspect_bus.setGeometry(QtCore.QRect(10, 10, 91, 31))
        self.inspect_bus.setObjectName("inspect_bus")
        self.tabWidget.addTab(self.inspect, "")
        self.html = QtGui.QWidget()
        self.html.setObjectName("html")
        self.html_webview = QtWebKit.QWebView(self.html)
        self.html_webview.setGeometry(QtCore.QRect(110, 10, 861, 581))
        self.html_webview.setUrl(QtCore.QUrl("about:blank"))
        self.html_webview.setRenderHints(QtGui.QPainter.SmoothPixmapTransform|QtGui.QPainter.TextAntialiasing)
        self.html_webview.setObjectName("html_webview")
        self.html_show = QtGui.QPushButton(self.html)
        self.html_show.setGeometry(QtCore.QRect(10, 10, 91, 31))
        self.html_show.setObjectName("html_show")
        self.tabWidget.addTab(self.html, "")
        self.res = QtGui.QWidget()
        self.res.setObjectName("res")
        self.res_impedance = QtGui.QPushButton(self.res)
        self.res_impedance.setGeometry(QtCore.QRect(10, 280, 91, 31))
        self.res_impedance.setObjectName("res_impedance")
        self.res_shunt = QtGui.QPushButton(self.res)
        self.res_shunt.setGeometry(QtCore.QRect(10, 250, 91, 31))
        self.res_shunt.setObjectName("res_shunt")
        self.res_xward = QtGui.QPushButton(self.res)
        self.res_xward.setGeometry(QtCore.QRect(10, 340, 91, 31))
        self.res_xward.setObjectName("res_xward")
        self.res_sgen = QtGui.QPushButton(self.res)
        self.res_sgen.setGeometry(QtCore.QRect(10, 100, 91, 31))
        self.res_sgen.setObjectName("res_sgen")
        self.res_ward = QtGui.QPushButton(self.res)
        self.res_ward.setGeometry(QtCore.QRect(10, 310, 91, 31))
        self.res_ward.setObjectName("res_ward")
        self.res_gen = QtGui.QPushButton(self.res)
        self.res_gen.setGeometry(QtCore.QRect(10, 220, 91, 31))
        self.res_gen.setObjectName("res_gen")
        self.res_message = QtWebKit.QWebView(self.res)
        self.res_message.setGeometry(QtCore.QRect(110, 10, 861, 551))
        self.res_message.setStyleSheet("\n"
"            table       {border-collapse: collapse;width: 100%;}\n"
"            tr:first    {background:#e1e1e1;}\n"
"            th,td       {text-align:left; border:1px solid #e1e1e1;}\n"
"            th          {background-color: #4CAF50;color: white;}\n"
"            tr:nth-child(even){background-color: #f2f2f2;}\n"
"          ")
        self.res_message.setUrl(QtCore.QUrl("about:blank"))
        self.res_message.setObjectName("res_message")
        self.res_bus = QtGui.QPushButton(self.res)
        self.res_bus.setGeometry(QtCore.QRect(10, 10, 91, 31))
        self.res_bus.setObjectName("res_bus")
        self.res_trafo = QtGui.QPushButton(self.res)
        self.res_trafo.setGeometry(QtCore.QRect(10, 160, 91, 31))
        self.res_trafo.setObjectName("res_trafo")
        self.res_ext_grid = QtGui.QPushButton(self.res)
        self.res_ext_grid.setGeometry(QtCore.QRect(10, 130, 91, 31))
        self.res_ext_grid.setObjectName("res_ext_grid")
        self.res_lines = QtGui.QPushButton(self.res)
        self.res_lines.setGeometry(QtCore.QRect(10, 40, 91, 31))
        self.res_lines.setObjectName("res_lines")
        self.res_trafo3w = QtGui.QPushButton(self.res)
        self.res_trafo3w.setGeometry(QtCore.QRect(10, 190, 91, 31))
        self.res_trafo3w.setObjectName("res_trafo3w")
        self.res_dcline = QtGui.QPushButton(self.res)
        self.res_dcline.setGeometry(QtCore.QRect(10, 370, 91, 31))
        self.res_dcline.setObjectName("res_dcline")
        self.res_load = QtGui.QPushButton(self.res)
        self.res_load.setGeometry(QtCore.QRect(10, 70, 91, 31))
        self.res_load.setObjectName("res_load")
        self.tabWidget.addTab(self.res, "")
        self.build = QtGui.QWidget()
        self.build.setObjectName("build")
        self.groupBox = QtGui.QGroupBox(self.build)
        self.groupBox.setGeometry(QtCore.QRect(110, 0, 121, 281))
        self.groupBox.setObjectName("groupBox")
        self.create_bus = QtGui.QRadioButton(self.groupBox)
        self.create_bus.setGeometry(QtCore.QRect(10, 50, 82, 17))
        self.create_bus.setObjectName("create_bus")
        self.create_line = QtGui.QRadioButton(self.groupBox)
        self.create_line.setGeometry(QtCore.QRect(10, 80, 82, 17))
        self.create_line.setObjectName("create_line")
        self.create_trafo = QtGui.QRadioButton(self.groupBox)
        self.create_trafo.setGeometry(QtCore.QRect(10, 110, 82, 17))
        self.create_trafo.setObjectName("create_trafo")
        self.create_edit_elements = QtGui.QRadioButton(self.groupBox)
        self.create_edit_elements.setGeometry(QtCore.QRect(10, 20, 82, 17))
        self.create_edit_elements.setChecked(True)
        self.create_edit_elements.setObjectName("create_edit_elements")
        self.create_ext_grid = QtGui.QRadioButton(self.groupBox)
        self.create_ext_grid.setGeometry(QtCore.QRect(10, 140, 101, 17))
        self.create_ext_grid.setObjectName("create_ext_grid")
        self.create_load = QtGui.QRadioButton(self.groupBox)
        self.create_load.setGeometry(QtCore.QRect(10, 170, 82, 17))
        self.create_load.setObjectName("create_load")
        self.create_gen = QtGui.QRadioButton(self.groupBox)
        self.create_gen.setGeometry(QtCore.QRect(10, 200, 82, 17))
        self.create_gen.setObjectName("create_gen")
        self.create_sgen = QtGui.QRadioButton(self.groupBox)
        self.create_sgen.setGeometry(QtCore.QRect(10, 230, 82, 17))
        self.create_sgen.setObjectName("create_sgen")
        self.build_shunt = QtGui.QPushButton(self.build)
        self.build_shunt.setGeometry(QtCore.QRect(10, 270, 91, 31))
        self.build_shunt.setObjectName("build_shunt")
        self.main_build_frame = QtGui.QWidget(self.build)
        self.main_build_frame.setGeometry(QtCore.QRect(240, 0, 801, 581))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_build_frame.sizePolicy().hasHeightForWidth())
        self.main_build_frame.setSizePolicy(sizePolicy)
        self.main_build_frame.setObjectName("main_build_frame")
        self.gridLayout = QtGui.QVBoxLayout(self.main_build_frame)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.build_impedance = QtGui.QPushButton(self.build)
        self.build_impedance.setGeometry(QtCore.QRect(10, 300, 91, 31))
        self.build_impedance.setObjectName("build_impedance")
        self.build_bus = QtGui.QPushButton(self.build)
        self.build_bus.setGeometry(QtCore.QRect(10, 0, 91, 31))
        self.build_bus.setObjectName("build_bus")
        self.build_message = QtGui.QTextBrowser(self.build)
        self.build_message.setGeometry(QtCore.QRect(10, 460, 221, 231))
        self.build_message.setFrameShape(QtGui.QFrame.Box)
        self.build_message.setObjectName("build_message")
        self.build_ward = QtGui.QPushButton(self.build)
        self.build_ward.setGeometry(QtCore.QRect(10, 330, 91, 31))
        self.build_ward.setObjectName("build_ward")
        self.build_measurement = QtGui.QPushButton(self.build)
        self.build_measurement.setGeometry(QtCore.QRect(10, 420, 91, 31))
        self.build_measurement.setObjectName("build_measurement")
        self.build_sgen = QtGui.QPushButton(self.build)
        self.build_sgen.setGeometry(QtCore.QRect(10, 120, 91, 31))
        self.build_sgen.setObjectName("build_sgen")
        self.build_switch = QtGui.QPushButton(self.build)
        self.build_switch.setGeometry(QtCore.QRect(10, 60, 91, 31))
        self.build_switch.setObjectName("build_switch")
        self.build_trafo3w = QtGui.QPushButton(self.build)
        self.build_trafo3w.setGeometry(QtCore.QRect(10, 210, 91, 31))
        self.build_trafo3w.setObjectName("build_trafo3w")
        self.build_gen = QtGui.QPushButton(self.build)
        self.build_gen.setGeometry(QtCore.QRect(10, 240, 91, 31))
        self.build_gen.setObjectName("build_gen")
        self.build_lines = QtGui.QPushButton(self.build)
        self.build_lines.setGeometry(QtCore.QRect(10, 30, 91, 31))
        self.build_lines.setObjectName("build_lines")
        self.build_ext_grid = QtGui.QPushButton(self.build)
        self.build_ext_grid.setGeometry(QtCore.QRect(10, 150, 91, 31))
        self.build_ext_grid.setObjectName("build_ext_grid")
        self.build_trafo = QtGui.QPushButton(self.build)
        self.build_trafo.setGeometry(QtCore.QRect(10, 180, 91, 31))
        self.build_trafo.setObjectName("build_trafo")
        self.build_load = QtGui.QPushButton(self.build)
        self.build_load.setGeometry(QtCore.QRect(10, 90, 91, 31))
        self.build_load.setObjectName("build_load")
        self.build_dcline = QtGui.QPushButton(self.build)
        self.build_dcline.setGeometry(QtCore.QRect(10, 390, 91, 31))
        self.build_dcline.setObjectName("build_dcline")
        self.build__xward = QtGui.QPushButton(self.build)
        self.build__xward.setGeometry(QtCore.QRect(10, 360, 91, 31))
        self.build__xward.setObjectName("build__xward")
        self.tabWidget.addTab(self.build, "")
        self.interpreter = QtGui.QWidget()
        self.interpreter.setObjectName("interpreter")
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.interpreter)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(120, 30, 711, 561))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.interpreter_vbox = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.interpreter_vbox.setContentsMargins(0, 0, 0, 0)
        self.interpreter_vbox.setObjectName("interpreter_vbox")
        self.tabWidget.addTab(self.interpreter, "")
        self.report = QtGui.QWidget()
        self.report.setObjectName("report")
        self.report_message = QtGui.QTextBrowser(self.report)
        self.report_message.setGeometry(QtCore.QRect(80, 20, 851, 571))
        self.report_message.setFrameShape(QtGui.QFrame.Box)
        self.report_message.setObjectName("report_message")
        self.tabWidget.addTab(self.report, "")
        self.help = QtGui.QWidget()
        self.help.setObjectName("help")
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.help)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(20, 20, 961, 581))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.webView = QtWebKit.QWebView(self.verticalLayoutWidget_3)
        self.webView.setUrl(QtCore.QUrl("http://pandapower.readthedocs.io/en/v1.3.0/"))
        self.webView.setObjectName("webView")
        self.verticalLayout_6.addWidget(self.webView)
        self.tabWidget.addTab(self.help, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        pandapower.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(pandapower)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1023, 21))
        self.menubar.setObjectName("menubar")
        pandapower.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(pandapower)
        self.statusbar.setObjectName("statusbar")
        pandapower.setStatusBar(self.statusbar)

        self.retranslateUi(pandapower)
        self.tabWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(pandapower)

    def retranslateUi(self, pandapower):
        pandapower.setWindowTitle(QtGui.QApplication.translate("pandapower", "pandapower", None, QtGui.QApplication.UnicodeUTF8))
        self.main_save.setText(QtGui.QApplication.translate("pandapower", "Save Network", None, QtGui.QApplication.UnicodeUTF8))
        self.main_losses.setText(QtGui.QApplication.translate("pandapower", "Losses Report", None, QtGui.QApplication.UnicodeUTF8))
        self.main_load.setText(QtGui.QApplication.translate("pandapower", "Load Network", None, QtGui.QApplication.UnicodeUTF8))
        self.main_solve.setText(QtGui.QApplication.translate("pandapower", "Solve (runpp)", None, QtGui.QApplication.UnicodeUTF8))
        self.main_empty.setText(QtGui.QApplication.translate("pandapower", "Empty Network", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.main), QtGui.QApplication.translate("pandapower", "Main Menu", None, QtGui.QApplication.UnicodeUTF8))
        self.inspect_ext_grid.setText(QtGui.QApplication.translate("pandapower", "External Grid", None, QtGui.QApplication.UnicodeUTF8))
        self.inspect_xward.setText(QtGui.QApplication.translate("pandapower", "Extended Ward", None, QtGui.QApplication.UnicodeUTF8))
        self.inspect_load.setText(QtGui.QApplication.translate("pandapower", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.inspect_dcline.setText(QtGui.QApplication.translate("pandapower", "DC Line", None, QtGui.QApplication.UnicodeUTF8))
        self.inspect_shunt.setText(QtGui.QApplication.translate("pandapower", "Shunt", None, QtGui.QApplication.UnicodeUTF8))
        self.inspect_trafo.setText(QtGui.QApplication.translate("pandapower", "Transformer", None, QtGui.QApplication.UnicodeUTF8))
        self.inspect_trafo3w.setText(QtGui.QApplication.translate("pandapower", "3W-Transformer", None, QtGui.QApplication.UnicodeUTF8))
        self.inspect_gen.setText(QtGui.QApplication.translate("pandapower", "Generator", None, QtGui.QApplication.UnicodeUTF8))
        self.inspect_impedance.setText(QtGui.QApplication.translate("pandapower", "Impedance", None, QtGui.QApplication.UnicodeUTF8))
        self.inspect_sgen.setText(QtGui.QApplication.translate("pandapower", "Stat Gen", None, QtGui.QApplication.UnicodeUTF8))
        self.inspect_switch.setText(QtGui.QApplication.translate("pandapower", "Switch", None, QtGui.QApplication.UnicodeUTF8))
        self.inspect_measurement.setText(QtGui.QApplication.translate("pandapower", "Measurement", None, QtGui.QApplication.UnicodeUTF8))
        self.inspect_ward.setText(QtGui.QApplication.translate("pandapower", "Ward", None, QtGui.QApplication.UnicodeUTF8))
        self.inspect_lines.setText(QtGui.QApplication.translate("pandapower", "Lines", None, QtGui.QApplication.UnicodeUTF8))
        self.inspect_bus.setText(QtGui.QApplication.translate("pandapower", "Bus", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.inspect), QtGui.QApplication.translate("pandapower", "Network Model", None, QtGui.QApplication.UnicodeUTF8))
        self.html_show.setText(QtGui.QApplication.translate("pandapower", "HTML", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.html), QtGui.QApplication.translate("pandapower", "HTML Report", None, QtGui.QApplication.UnicodeUTF8))
        self.res_impedance.setText(QtGui.QApplication.translate("pandapower", "Impedance", None, QtGui.QApplication.UnicodeUTF8))
        self.res_shunt.setText(QtGui.QApplication.translate("pandapower", "Shunt", None, QtGui.QApplication.UnicodeUTF8))
        self.res_xward.setText(QtGui.QApplication.translate("pandapower", "Extended Ward", None, QtGui.QApplication.UnicodeUTF8))
        self.res_sgen.setText(QtGui.QApplication.translate("pandapower", "Stat Gen", None, QtGui.QApplication.UnicodeUTF8))
        self.res_ward.setText(QtGui.QApplication.translate("pandapower", "Ward", None, QtGui.QApplication.UnicodeUTF8))
        self.res_gen.setText(QtGui.QApplication.translate("pandapower", "Generator", None, QtGui.QApplication.UnicodeUTF8))
        self.res_bus.setText(QtGui.QApplication.translate("pandapower", "Bus", None, QtGui.QApplication.UnicodeUTF8))
        self.res_trafo.setText(QtGui.QApplication.translate("pandapower", "Transformer", None, QtGui.QApplication.UnicodeUTF8))
        self.res_ext_grid.setText(QtGui.QApplication.translate("pandapower", "External Grid", None, QtGui.QApplication.UnicodeUTF8))
        self.res_lines.setText(QtGui.QApplication.translate("pandapower", "Lines", None, QtGui.QApplication.UnicodeUTF8))
        self.res_trafo3w.setText(QtGui.QApplication.translate("pandapower", "3W-Transformer", None, QtGui.QApplication.UnicodeUTF8))
        self.res_dcline.setText(QtGui.QApplication.translate("pandapower", "DC Line", None, QtGui.QApplication.UnicodeUTF8))
        self.res_load.setText(QtGui.QApplication.translate("pandapower", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.res), QtGui.QApplication.translate("pandapower", "Load Flow Results", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("pandapower", "Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.create_bus.setText(QtGui.QApplication.translate("pandapower", "Create Bus", None, QtGui.QApplication.UnicodeUTF8))
        self.create_line.setText(QtGui.QApplication.translate("pandapower", "Create Line", None, QtGui.QApplication.UnicodeUTF8))
        self.create_trafo.setText(QtGui.QApplication.translate("pandapower", "Create Trafo", None, QtGui.QApplication.UnicodeUTF8))
        self.create_edit_elements.setText(QtGui.QApplication.translate("pandapower", "Edit Elements", None, QtGui.QApplication.UnicodeUTF8))
        self.create_ext_grid.setText(QtGui.QApplication.translate("pandapower", "Create Ext grid", None, QtGui.QApplication.UnicodeUTF8))
        self.create_load.setText(QtGui.QApplication.translate("pandapower", "Create Load", None, QtGui.QApplication.UnicodeUTF8))
        self.create_gen.setText(QtGui.QApplication.translate("pandapower", "Create Gen", None, QtGui.QApplication.UnicodeUTF8))
        self.create_sgen.setText(QtGui.QApplication.translate("pandapower", "Create sGen", None, QtGui.QApplication.UnicodeUTF8))
        self.build_shunt.setText(QtGui.QApplication.translate("pandapower", "Shunt", None, QtGui.QApplication.UnicodeUTF8))
        self.build_impedance.setText(QtGui.QApplication.translate("pandapower", "Impedance", None, QtGui.QApplication.UnicodeUTF8))
        self.build_bus.setText(QtGui.QApplication.translate("pandapower", "Bus", None, QtGui.QApplication.UnicodeUTF8))
        self.build_ward.setText(QtGui.QApplication.translate("pandapower", "Ward", None, QtGui.QApplication.UnicodeUTF8))
        self.build_measurement.setText(QtGui.QApplication.translate("pandapower", "Measurement", None, QtGui.QApplication.UnicodeUTF8))
        self.build_sgen.setText(QtGui.QApplication.translate("pandapower", "Stat Gen", None, QtGui.QApplication.UnicodeUTF8))
        self.build_switch.setText(QtGui.QApplication.translate("pandapower", "Switch", None, QtGui.QApplication.UnicodeUTF8))
        self.build_trafo3w.setText(QtGui.QApplication.translate("pandapower", "3W-Transformer", None, QtGui.QApplication.UnicodeUTF8))
        self.build_gen.setText(QtGui.QApplication.translate("pandapower", "Generator", None, QtGui.QApplication.UnicodeUTF8))
        self.build_lines.setText(QtGui.QApplication.translate("pandapower", "Lines", None, QtGui.QApplication.UnicodeUTF8))
        self.build_ext_grid.setText(QtGui.QApplication.translate("pandapower", "External Grid", None, QtGui.QApplication.UnicodeUTF8))
        self.build_trafo.setText(QtGui.QApplication.translate("pandapower", "Transformer", None, QtGui.QApplication.UnicodeUTF8))
        self.build_load.setText(QtGui.QApplication.translate("pandapower", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.build_dcline.setText(QtGui.QApplication.translate("pandapower", "DC Line", None, QtGui.QApplication.UnicodeUTF8))
        self.build__xward.setText(QtGui.QApplication.translate("pandapower", "Extended Ward", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.build), QtGui.QApplication.translate("pandapower", "Add Elements", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.interpreter), QtGui.QApplication.translate("pandapower", "Interpreter", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.report), QtGui.QApplication.translate("pandapower", "Report", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.help), QtGui.QApplication.translate("pandapower", "Documentation", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("pandapower", "About", None, QtGui.QApplication.UnicodeUTF8))

from PySide import QtWebKit

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    pandapower = QtGui.QMainWindow()
    ui = Ui_pandapower()
    ui.setupUi(pandapower)
    pandapower.show()
    sys.exit(app.exec_())

